default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: comment_development
  host: localhost
  port: 5432
  variables:
    statement_timeout: 60000

development:
  <<: *default

production:
  <<: *default
