Message.create([
  { text: "Migrer sereinement du Monolithe aux microservices" },
  { text: "My 2 cents on testing best practices" },
  { text: "Éliminer définitivement vos bugs grâce à la méthode PISCARE" },
  { text: "Ajouter la visibilité des CVEs dans rubygems.org" },
  { text: "L'archi d'un backoffice" },
  { text: "Le chaînage des scopes dans Active Record" },
  { text: "Comment nous avons divisé les bugs par 3.5 en un an" },
  { text: "News ParisRB / RubyBaguette" },
  { text: "Nagle algorithm et delayed ack" },
  { text: "Level up your Capybara acceptance tests using SitePrism" },
  { text: "Sorbet in practice" },
  { text: "Business logic & Data integrity" },
  { text: "Produire du logiciel en coopérative ouvrière - Pourquoi Rails a été l'outil parfait pour concevoir Cyke" },
  { text: "Rails : XSS protection" },
  { text: "How music works, using Ruby" },
  { text: "Securing Software Supply Chain" },
  { text: "No Risk, No Fun : dédramatiser sans déresponsabiliser" },
  { text: "Quel type de tests dois-je écrire ?" },
  { text: "Modéliser des process métier en combinant state machine et STI" },
  { text: "On a recruté un.e dev junior ! AMA" },
  { text: "Comment on a industrialisé le développement et le testing de notre API" },
  { text: "Commit comme un hipster avec Gitmoji !" },
  { text: "Implementing blackout period on puma workers" },
  { text: "Utilisation de bases de données : retour d'expérience" },
  { text: "Service Objects, la brique manquante de Rails" },
  { text: "Paris.rb devient Baguette.rb ?" },
  { text: "React on Rails: le meilleur des 2 mondes" },
  { text: "Comment faire tenir son code sur un ticket de métro ? 🎫" },
  { text: "Les 10 erreurs les plus courante en entretien technique" },
  { text: "Build a web app with Dry-System" },
  { text: "Redis avec Heroku - Pourquoi et comment séparer son cache" },
  { text: "Comment on a amélioré le lien back-front en utilisant des fichiers openAPI" },
  { text: "Sauvegarder les emails : pourquoi, comment, itérations" },
  { text: "Comment j’ai rendu mon appli 3 fois plus rapide" },
  { text: "Que s'est il passé avec mimemagic?" },
  { text: "implémenter DROP COLUMN SQLite natif dans ActiveRecord" },
  { text: "Garder une trace de vos migrations" },
  { text: "Rendre Timecop ruby 3.1 compatible" },
  { text: "Graphiti" },
  { text: "Exception Matchers" },
  { text: "Une méthode pour tester les race conditions et problèmes de thread safety" },
  { text: "Mise à jour automatisée de Gems avec Dependabot" },
  { text: "PostgreSQL in production" },
  { text: "Improve your app reliability using Circuit Breaker" },
  { text: "Le guide RGPD du développeur" },
  { text: "L'autogestion dans une équipe dev" },
  { text: "Atteindre 100% de génération de code sur Rails" },
  { text: "MongoDB in production" },
  { text: "Travailler avec de l'IoT en production sous Rails" },
  { text: "Comment se plaindre efficacement" },
  { text: "Importer des fichiers Excel" },
  { text: "De maître à élève" },
  { text: "Zog-Zog : trucs idiots avec Ruby et Git" },
  { text: "Petit tour des serveurs Web Ruby" },
  { text: "Je fais du ruby pourtant je commit du C 🤔" },
  { text: "Devenez CTO en 20mn" },
  { text: "Voyages dans les réseaux de neurones" },
  { text: "Circuit Breaker pattern" },
  { text: "gRPC Kesako?" },
  { text: "ROM.rb retour d'expérience" },
  { text: "Sidekiq scaling: Workers vs Processes" },
  { text: "From 0 to 1 (business)" },
  { text: "Acceptance Testing in Ruby" },
  { text: "Limiting code execution time in Ruby" },
  { text: "Black Magic to Build Resilient API Dependencies (story of integrations with enterprise APIs like eBay, UPS, DHL, Russian Post and so on)" },
  { text: "String Similarity Algorithms Compared" },
  { text: "A la rencontre de Minimax" },
  { text: "1h Foncteurs Applicatifs et Monades" },
  { text: "From tribal knowledge to glorious automation" },
  { text: "Astuces pour le debugging" },
  { text: "Structure de données et Complexité" },
  { text: "Mise en conformité post RGPD, le REX Fidzup" },
  { text: "Make your microservices converge!" },
  { text: "Restructurer ses équipes en squads" },
  { text: "Ruby memory, ActiveRecord et Draper, une histoire de performance" },
  { text: "4 \"Code smells\" : un guide de simplification" },
  { text: "Benchmarker avec micro_bench" },
  { text: "Comment faire évoluer une app Rails de + de 6 ans" },
  { text: "Tom Hirschfield's 10 rules of thumb" },
  { text: "idempotency with rack" },
  { text: "Comparaison d'algorithmes d'apprentissage" },
  { text: "Machine Learning - théorie" },
  { text: "Créer un nouveau Cop (Rubocop)" },
  { text: "Déployer un blog Jekyll sur OVH" },
  { text: "Les syntaxes avec { } peuvent être 😈" },
  { text: "Récupérer la devise en cours sous Rails" },
  { text: "Continuous Delivery for Rails App with Docker and Gitlab" },
  { text: "Organiser vos idee avec Dry-Transaction" },
  { text: "🙋🙋‍♂️welcome @kaspth" },
  { text: "Quitter le \"papa/maman\" en 18 min 42 sec" },
  { text: "Tests aquatiques 💧" },
  { text: "Maintenance et refactoring d'une application Rails - 3 tips" },
  { text: "Polymorphic associations and Single-table inheritance in rails" },
  { text: "How an engineer learns japanese" },
  { text: "L'anti-pattern ActiveRecord" },
  { text: "Decorators" },
  { text: "Bien tester des ActiveJobs et ne pas se faire avoir par la désérialisation" },
  { text: "Le debugging n'a jamais été aussi cool 😎" },
  { text: "Boostez votre travail d'équipe avec les Randoris" },
  { text: "Envufy: une extension pratique en 5 minutes" },
  { text: "Un truc avec ruby et raspberry" },
  { text: "Regexp Implementation in Ruby" },
  { text: "Comment utiliser flamegraph pour améliorer ses perfs" },
  { text: "Demystifying blocks" },
  { text: "SMS with Twilio & Rails" },
  { text: "The Life and Death of a Rails App" },
  { text: "Présentation d'Hanami" },
  { text: "Heroku Scheduler : faire des tasks régulières" },
  { text: "Hunting flaky tests" },
  { text: "Le cadeau piégé, ou comment j'ai rétroengineeré un tracker GPS et l'API Strava" },
  { text: "Introduction à GraphQL avec graphql-ruby " },
  { text: "Lancement de Ruby mentors" },
  { text: "Oubliez Foreman, voici Overmind" },
  { text: "Gem gon pour récupérer ses données d'un controller en ruby à ses fichiers javascript" },
  { text: "Extracts from \"Clean code\"" },
  { text: "Présentation des services Rails et cas d'utilisation Kudoz" },
  { text: "Trailblazer" },
  { text: "Faire des review automatique de code sur GitHub avec Rubocop, Pronto et CircleCI" },
  { text: "Les conséquences du RGPD pour les développeurs" },
  { text: "Comment accueillir, accompagner et faire grandir un développeur junior " },
  { text: "json:api with jsonapi_suite - sideloading & sideposting : one endpoint to rule-them-all" },
  { text: "How can automation help with development practices" },
  { text: "La Méthode du Capitaine" },
  { text: "MRuby sur Raspberry" },
  { text: "Science up your ruby with scientist !" },
  { text: "Rubocop" },
  { text: "Zero Downtime Deploys" },
  { text: "The DevOps culture & Ruby" },
  { text: "Accélérez vos tests" },
  { text: "Snapchat Takeover Women in Tech" },
  { text: "def <3" },
  { text: "Utiliser API.ai pour mettre en place un bot rapidement" },
  { text: "Tepee, un outil de gestion de configuration pour les braves" },
  { text: "Git - Quel workflow utiliser ?" },
  { text: "Enseigner est apprendre : devenez un·e meilleur·e dev en partageant vos connaissances" },
  { text: "Configuration de l'environnement de déploiement avec Gitlab - Hexappsetup" },
  { text: "VCR - testez vos call http" },
  { text: "Un Gemfile lisible" },
  { text: "Le Semantic Versioning dans une app web - pourquoi?" },
  { text: "Des « user stories » aux « job stories » (avec exemples)" },
  { text: "/Expressions rationnelles/" },
  { text: "Simulating Deliveries at Stuart" },
  { text: "News : PolyConf" },
  { text: "How are we testing a \"Voice\" service at Aircall?" },
  { text: "Forgotten HTML " },
  { text: "Utilisez Mutant pour améliorer votre code" },
  { text: "Internationalize your rails app (the stuff they don't tell you)" },
  { text: "Faire un bot en 20 minutes - live coding" },
  { text: "reads for the next 10 years" },
  { text: "La différence entre to_s et to_str" },
  { text: "MySQL 5.6, 5.7 and what's coming in 8.0" },
  { text: "Reducing a gem from size from 147MB to 2.4MB" },
  { text: "Qu'est ce que j'ai appris en 10 ans de rails" },
  { text: "Rack" },
  { text: "Death to the Staging Env" },
  { text: "Dix ans de lecture" },
  { text: "DotScale & concours" },
  { text: "dev.learn(stuff)" },
  { text: "Ruby et ses blocs" },
  { text: "Donjons & Dragons & Modules" },
  { text: "Design patterns for Rails Engines" },
  { text: "Tribes, Guilds and Squads chez JobTeaser" },
  { text: "Simulation du 'Manchester Baby'" },
  { text: "Réalité Virtuelle et Ruby" },
  { text: "Local SaaS: Comment développer une admin SaaS qui s'intègre directement dans l'application de vos clients" },
  { text: "FlameGraph" },
  { text: "Just-a-Website Manifesto" },
  { text: "Mastering Arel (2013 @danschultz)" },
  { text: "From darkness to light" },
  { text: "8⃣ Learned Helplessness -> Learned Optimism" },
  { text: "8⃣ Lessons learned from a week blind: from tech to human experience" },
  { text: "8⃣ Ruby Together" },
  { text: "6⃣ Ce que j'aurais aimé entendre il y a 1 an : faites un petit projet OS ;)" },
  { text: "6⃣ RubyTogether & CallbackWomen" },
  { text: "6⃣ Comment construire un newsfeed de plusieurs modèles" },
  { text: "6⃣ Dix choses que j'ai apprises sur le dev web grâce à Megadeth" },
  { text: "Paris Ruby Workshop 💎 Rails Thematic Workshops" },
  { text: "RailsGirls #8 25/26 nov 💖 NUMA 6 dec 💝 Exceptional 8 dec" },
  { text: "The benefits of personal projects" },
  { text: "Simplify your Ruby setup with Docker" },
  { text: "Mise en place d'une architecture Web en Crystal" },
  { text: "Macros, Rules and Roleplay" },
  { text: "Everyone's Lying to You: how to take the guesswork customer interviews" },
  { text: "Être cyberpunk en entreprise" },
  { text: "Comment recruter un(e) développeur(se) junior" },
  { text: "Refactoring grâce aux Concerns et Presenters" },
  { text: "Repenser son workflow avec un piano USB 32 touches et du Ruby" },
  { text: "De Maître à Élève" },
  { text: "Sous le capot de la Locomotive" },
  { text: "Continous Security" },
  { text: "Qu'est-ce qui nous motive vraiment ?" },
  { text: "3. ReactRB la suite ;-)" },
  { text: "1. Parser des CSV avec ruby" },
  { text: "2. How (not) to use mocks" },
  { text: "How we switched from a monolithic app to isolated services - 3 takeaways" },
  { text: "Ruby & le travel & les bots, compatible ?" },
  { text: "Graph Theory behind Immutable.js" },
  { text: "How not to design a state machine" },
  { text: "Bugmastery" },
  { text: "CSP: from zero to production in 30 seconds" },
  { text: "Security Tip #2 - Content Security Policy" },
  { text: "How to start blogging" },
  { text: "Plugin Algolia pour Jekyll" },
  { text: "No Downtime Deployment" },
  { text: "Having fun with ruby (Sonic Pi & Dare)" },
  { text: "Daskit - attendees feedback with ActionCable" },
  { text: "Singa - aide aux réfugiés" },
  { text: "Security Tip #1" },
  { text: "Parlons rapidement d'optimisation de performance en Ruby" },
  { text: "The Kemal framework - Crystal's Sinatra" },
  { text: "The Crystal Programming Language" },
  { text: "Resource Fool" },
  { text: "Remote Work Tools" },
  { text: "Practices of a remote extreme programmer" },
  { text: "Getting Things Done" },
  { text: "Ember.JS" },
  { text: "CSS Flags - compagnonnage & vexillologie" },
  { text: "What is Rack?" },
  { text: "First app with action-cable" },
  { text: "Why I don't network on LinkedIn" },
  { text: "Futur, Technologie, et Magie" },
  { text: "Tune your app perf (and get fit for summer)" },
  { text: "Hacked via OWASP Top 10? Not “advanced” nor “sophisticated”" },
  { text: "scalingo_databases_rake_tasks & other tricks" },
  { text: "Heroku workflow" },
  { text: "Working with Simple Tools" },
  { text: "Fix - Simple, stupid testing framework for Ruby" },
  { text: "service objects, light service, interactor and waterfall" },
  { text: "Reprise des CodeLabs !" },
  { text: "Prenez le contrôle de votre réseau avec Ownlan" },
  { text: "Waste less time on bugs with exploratory testing" },
  { text: "What's new in Ruby 2.3?" },
  { text: "Using UUID in ActiveRecord with PostgreSQL" },
  { text: "Commencer avec React.rb" },
  { text: "Working with Rails Engines" },
  { text: "My first ActionCable app" },
  { text: "Trailblazer" },
  { text: "Ruby keyword args from the parser to the VM" },
  { text: "Web Animation Performance" },
  { text: "💝 24pullrequests.com / thecodelesscode.com" },
  { text: "❄️ Inuit, c'est inouï" },
  { text: "🎁 Surprise ;)" },
  { text: "🎅 Storexplore transforme les boutiques en ligne en API" },
  { text: "🎶 How we refactored our logging system" },
  { text: "Instrument Rack to visualize requests processing" },
  { text: "some Pry features" },
  { text: "5 Workplace Hacks" },
  { text: "Présentation de la gem synvert" },
  { text: "React.rb, React... en ruby :)" },
  { text: "Moving data with Kiba ETL" },
  { text: "De quoi voulez-vous parler ?" },
  { text: "JobTeaser" },
  { text: "Clean up your specs with Page Objects" },
  { text: "Add Rails security to your Continuous Development" },
  { text: "Le CTO à 2€ [1/2]" },
  { text: "http://tinyurl.com/ruby-paris-feedback" },
  { text: "http://tinyurl.com/candidature-railsgirlsparis-6" },
  { text: "The C in Ruby - `%`" },
  { text: "Hiérarchie des classes et modules principaux de Ruby" },
  { text: "Mon premier mini machine learning en Ruby" },
  { text: "Less Code" },
  { text: "Comment recruter et comprendre un CTO quand on ne connait rien à la technique" },
  { text: "Remote Freelancer, pourquoi pas moi ?" },
  { text: "Evil Gems" },
  { text: "Materialize" },
  { text: "Le fonctionnement interne de Rails" },
  { text: "Il faut bien bosser dans le web alors autant que ça se passe bien" },
  { text: "🔈 Concours de PR / Paris 5 juin" },
  { text: "🔈 RailsGirls Paris 2015 - juillet" },
  { text: "Building and Testing Resilient Applications" },
  { text: "CSS Grid : découvrez le futur de la mise en page des sites web" },
  { text: "Organize your assets with Rails" },
  { text: "🔈 atelier stratégie des Apps - Paris, 21 mai, 16h" },
  { text: "🔈 dotScale 2015" },
  { text: "Développeurs, faites votre place dans la santé" },
  { text: "💻 RubyMotion : live coding Android + iOS" },
  { text: "💻 Science et magie" },
  { text: "Concevoir des logiciels : structurer son code au-delà de l'algorithme" },
  { text: "De Ruby & Rails aux microservices en Elixir & Phoenix" },
  { text: "On a jeté le café avec l'eau du bain" },
  { text: "Speed your app creation with templates" },
  { text: "Fun with docker in Ruby " },
  { text: "Comment négocier son salaire avec tact et efficacité" },
  { text: "PostgreSQL Dashboard : A real-time monitoring screen based on Dashing and Sinatra" },
  { text: "Il est temps d'utiliser les Flexbox en CSS" },
  { text: "Angular ou Backbone, choisir en 2015" },
  { text: "Pourquoi vous allez contribuer à un projet open source" },
  { text: "GitHub Awards : Analyse des data GitHub" },
  { text: "Grace Murray Hopper, la créatrice du premier compilateur" },
  { text: "Dependency Sorting with TSort" },
  { text: "Achieving full-stack reactivity to create modern apps with MeteorJS" },
  { text: "Hexagonal Architecture" },
  { text: "Make your business SPOF-less" },
  { text: "Unix shortcuts" },
  { text: "42Grounds.io: Share code behavior" },
  { text: "Pourquoi je passe au business model open source" },
  { text: "Ruby Benchmark - Ne faites pas confiance à votre instinct" },
  { text: "Aller au-delà de ce que vous croyez pouvoir aller (ou faire)" },
  { text: "ActiveAdmin" },
  { text: "Booster son CV" },
  { text: "20 ans de programmation ou pourquoi j'aime Ruby" },
  { text: "Zombie, Braaaaaaaaain, and Ruby" },
  { text: "Paris.rb : MVC avec Erlang et Ruby" },
  { text: "Entendre avec les yeux, voir avec les oreilles" },
  { text: "6 mois pour rendre un-e débutant-e employable" },
  { text: "Stresser son app pour moins stresser (avec JMeter)" },
  { text: "Les extensions de browser" },
  { text: "Moteurs d'optimisation avec Ruby On Rails : Retour d'expérience" },
  { text: "CareerBuilder / lesjeudis" },
  { text: "Speed dating ruby - Retours d'expérience" },
  { text: "Top gems to start a new project" },
  { text: "Ten commandments of egoless programming" },
  { text: "Effets de la sociologie sur les devs" },
  { text: "Unidecoder" },
  { text: "Construisons une pyramide !" },
  { text: "rspec-preloader : Démarrer rspec instantanément" },
  { text: "Gérer les heures ouvrées avec working_hours" },
  { text: "RailsGirls Paris #4" },
  { text: "PullReview" },
  { text: "Présentation Prelang" },
  { text: "Différences/liens entre Cucumber, Capybara/Webrat, Selenium, RSpec, FactoryGirl" },
  { text: "Instrumenting your ruby infrastructure with the ELK stack" },
  { text: "Être développeur ruby au Japon" },
  { text: "Ce que j'ai appris en ratant mon side project" },
  { text: "Ruby is not only for your servers anymore" },
  { text: "Mon premier mois dans une start-up" },
  { text: "Un peu de contrôle" },
  { text: "10 Rails Pro tips" },
  { text: "Rails on Rio (Rails fait tourner la coupe du monde de foot)" },
  { text: "IT Management" },
  { text: "J'ai une idée - je vais en faire une webapp... Ou pas." },
  { text: "Text Tools" },
  { text: "Comment générer du CA et des clients sans budget marketing ?" },
  { text: "Localize your files in Mongoid | A mongoid Paperclip fork" },
  { text: "Zapper" },
  { text: "Pub / Sub in Ruby" },
  { text: "SSH pour un dévelopeur Ruby" },
  { text: "Managing dynamic domains with Rails" },
  { text: "Table Driven Testing" },
  { text: "Get Slim!" },
  { text: "Linters" },
  { text: "Reverse engineering du QLobe" },
  { text: "Un sitemap generator" },
  { text: "Live Coding - Mon site perso en 20 minutes avec Rails+Olala" },
  { text: "\"Infrastructure as code\" avec Chef" },
  { text: "From a development work flow to a flow that works" },
  { text: "12 mois dans la peau d'une application d'entreprise en mode LEAN STARTUP" },
  { text: "Build Realtime Search with Algolia" },
  { text: "Crawling the web using Import.io & Sidekiq" },
  { text: "Rails as a build tool or why Rails is awesome ( or FU** Grunt)" },
  { text: "The treasures of Ruby core, one for each day" },
  { text: "A/B Testing on Rails" },
  { text: "Ruby par la pratique" },
  { text: "Bye Google Maps, welcome Mapbox: 10 raisons pour migrer tout de suite" },
  { text: "Trouvez vous un partenaire de jeu" },
  { text: "Et si quelqu'un venait de la part de Cassandre, Ouvre-lui tôt la porte et ne le fais pas attendre" },
  { text: "Cherche coachs pour initier des collégiennes à la programmation" },
  { text: "Alzheimer's Shell" },
  { text: "Multi-tenant/lang application" },
  { text: "Known unknowns" },
  { text: "Le Code est un jeu de Piste: Codez pour des humains, pas pour des machines" },
  { text: "Fake your files" },
  { text: "Pry as replacement for irb and debugger" },
  { text: "Predictive analysis in real time with Ruby and R" },
  { text: "Relecture POODR - Single Responsibility" },
  { text: "Pragmatic Web Components" },
  { text: "Server-Sent Events" },
  { text: "Form Objects" },
  { text: "Bootstrapping d'un SaaS" },
  { text: "ActiveRecord Serialization" },
  { text: "Applications Mobiles Natives" },
  { text: "gmaps4rails" },
  { text: "ActionController::Live" },
  { text: "Palette de couleur Web" },
  { text: "Zeus & Zeus Parallel tests" },
  { text: "Recent technical advances in Passenger" },
  { text: "La bibliothèque Gosu" },
  { text: "HTTP Cache en Rails 4" },
  { text: "Discourse : la plateforme de discussion nouvelle génération" },
  { text: "REST with Her" },
  { text: "State Machine" },
  { text: "Manuel de survie de l'innovateur en entreprise" },
  { text: "Sécuriser son application Ruby on Rails" },
  { text: "Meteor 101 : A better way to build web apps 100% in Javascript" },
  { text: "RuLu 2013" },
  { text: "Les BrownBagLunch (BBL)" },
  { text: "Must Have des gems de débug visuel pour Rails" },
  { text: "Recréer EventMachine à partir de zéro, en Ruby" },
  { text: "Make Hypermedia APIs in Ruby" },
  { text: "Une API rapide et de qualité avec Weasel-Diesel" },
  { text: "Do we deserve the Wooden Spoon?" },
  { text: "Hack your brain!" },
  { text: "How (not) to design a modern API legacy systems" },
  { text: "Comment j’ai trouvé une copine avec Node.js" },
  { text: "Comment appréhender RoR quand on vient du développement web traditionnel ?" },
  { text: "Multiplayer Game" },
  { text: "Réseautez ! (qui est freelance, qui cherche un job?)" },
  { text: "Apprendre Rails en partant de zéro" },
  { text: "Annonce de la conférence dotRB" },
  { text: "Vagrant : Faire du dev dans une VM" },
  { text: "Rubymotion" },
  { text: "Créer une API avec Netty et JRuby" },
  { text: "Chef Solo & Capistrano" },
  { text: "Ruby Press Pack" },
  { text: "Ruby et DCI" },
  { text: "Gérer son auto-entreprise et créer une SAS avant de se lancer" },
  { text: "Websockets Rails" },
  { text: "Coconut Freelancing" },
  { text: "Lightning Talks Suck!" },
  { text: "AXLSX Vos fichiers Excel tout simplement en Ruby" },
  { text: "Responsive Web Design" },
  { text: "EventMachine et websocket " },
  { text: "SOA on Rails" },
  { text: "Santé des Geeks" },
  { text: "Block, Proc et Lambda" },
  { text: "De Rails 2.0 A Rails 4.0" },
  { text: "Mustdown" },
  { text: "ObjectID in MongoDB" },
  { text: "It's time to learn the basics!" },
  { text: "Ce que j'aurais voulu savoir" },
  { text: "LAB - architectural kata" },
  { text: "Pas clair mais super cool (owf? wlw?)." },
  { text: "Présentation de AngularJS et comment l'intégrer à Rails" },
  { text: "Draper" },
  { text: "ActiveModelSerializers" },
  { text: "tent.io" },
  { text: "Validate-website - Web crawler for checking the validity of your documents" },
  { text: "Vos RegExps sont fausses" },
  { text: "Présentation de la gem rails-canhaz et introduction à la création d'une gem" },
  { text: "Exceptions in Ruby Tips and tricks" },
  { text: "Responsive Design" },
  { text: "Founder & CEO Verseau" },
  { text: "La Prévoyance et la retraite des indépendants" },
  { text: "Réaliser une application web avec Sinatra, knockout.js et CoffeeScript" },
  { text: "Lean Startup - développement en flux tendu grâce au cycle Build / Measure / Learn" },
  { text: "Ariane" },
  { text: "La concurrence en Ruby - (Boldr) – Asynchronie avec Ruby" },
  { text: "Measure anything, measure everything : suivre son application Rails en temps réel." },
  { text: "Salesforce/Heroku/Rails WTF ?" },
  { text: "Quelques patterns asynchrones, d'EM à Celluloid" },
  { text: "PJAX : HTML5 pushState & Ajax dans Rails en 5 minutes" },
  { text: "Vendez Ruby on Rails à votre patron" },
  { text: "Enlarge your Apdex Naturally! (Proven methods to enhance your Rails performance when trafic increases X times)" },
  { text: "MongoDB 2" },
  { text: "Reprendre un (gros) projet Ruby on Rails" },
  { text: "OAuth2 en bref" },
  { text: "Manage Open Source Project" },
  { text: "Le projet de Geekli.st" },
  { text: "Pourquoi Ruby on Rails ?" },
  { text: "Retour d'expérience sur Liquid, et présentation de Solid" },
  { text: "Présentation de MongoDB / Mongoid" },
  { text: "Rails Devise Cancan" },
  { text: "Commander" },
  { text: "RubyLive" },
  { text: "GetText, une alternative à i18n standard" },
])